version: "3.9"

services:
  postgres:
    container_name: vaxly_dev_postgres
    image: postgres:16
    environment:
      POSTGRES_USER: qfen
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vaxly_dev
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5332:5432"
    networks:
      - backend
    restart: unless-stopped

  redis:
    container_name: vaxly_dev_redis
    image: redis:7.2
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge

volumes:
  db_data:
