spring:
  application:
    name: scheduler-service
  data:
    redis:
      host:
      port:
  cloud:
    aws:
      region:
        static:
      credentials:
        access-key:
        secret-key:
      sqs:
        queue-url:

scheduler:
  topPairsCount: 4
  fixedRate: 30000 # 30 seconds
  refreshInterval: 30000