spring:
  application:
    name: scheduler-service
  data:
    redis:
      host: redis
      port: 6379
  cloud:
    aws:
      region:
        static: us-east-2
      credentials:
        access-key: AKIA55OMVDCRW5Q5SBA3
        secret-key: 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
      sqs:
        queue-url: https://sqs.us-east-2.amazonaws.com/956596295843/vaxly-dev-sqs-queue

scheduler:
  topPairsCount: 4
  fixedRate: 30000 # 30 seconds
  refreshInterval: 30000