spring:
  datasource:
    url: jdbc:tc:postgresql:15:///qfen
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: qfen
    password: qfen
  jpa:
    hibernate:
      ddl-auto: create-drop
  data:
    redis:
      port: 6379
      host: localhost

