spring:
  datasource:
    url:
    driver-class-name:
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379


  flyway:
    clean-on-validation-error: true

  cloud:
    aws:
      region:
        static:
      credentials:
        access-key:
        secret-key:
      sqs:
        queue-url:

security:
  cognito:
    client-id:
    client-secret:
    token-endpoint:
    scope:

external:
  api:
    base-url:
