spring:
  datasource:
    url: jdbc:h2:mem:vaxlydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379


  flyway:
    clean-on-validation-error: true

security:
  cognito:
    client-id: 3ke2fgifpd0o298bvan5ik3gsp
    client-secret: 16rikb8h67fb3d2as890iiq3j42pc0lnk77f87ohb3sjhu99ljlg
    token-endpoint: https://us-east-2igrqq8rhb.auth.us-east-2.amazoncognito.com/oauth2/token
    scope: historical-service-api/historical-rates-reader

external:
  api:
    base-url: http://localhost:8080/api/v1/historical-rates/
