CREATE TABLE historical_rates
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    currency_pair   VARCHAR(255)                             NOT NULL,
    rate            DECIMAL(19, 8)                           NOT NULL,
    source          VARCHAR(255)                           NOT NULL,
    last_updated_at TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    CONSTRAINT pk_historical_rates PRIMARY KEY (id)
);

ALTER TABLE historical_rates
    ADD CONSTRAINT uc_historical_rates_currencypair UNIQUE (currency_pair);