spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/vaxly_dev
    username: qfen
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
